sudo: false
language: python
python:
  - "3.9"
before_install:
  - nvm install node 
before_script:
  - npm install -g serverless
script:
  - make
notifications:
  email:
    recipients:
      - tdhopper@gmail.com
    on_success: change
on_failure: always
